// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuxL0j1qFW1jxnVpjex9rkaOkDEe6cm-U',
    appId: '1:770345713614:web:cd0495618a159eceb8f59f',
    messagingSenderId: '770345713614',
    projectId: 'paeria-570f6',
    authDomain: 'paeria-570f6.firebaseapp.com',
    storageBucket: 'paeria-570f6.firebasestorage.app',
    measurementId: 'G-NP4CZG4KBD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm7PM0k5J5mfgMH5Aa9KGe05zZ2drNjcQ',
    appId: '1:770345713614:android:370be239209d71d8b8f59f',
    messagingSenderId: '770345713614',
    projectId: 'paeria-570f6',
    storageBucket: 'paeria-570f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVJ5IJaNmHeaJWhsuFTjnGInNShLT0zvw',
    appId: '1:770345713614:ios:4861e192aa6c349bb8f59f',
    messagingSenderId: '770345713614',
    projectId: 'paeria-570f6',
    storageBucket: 'paeria-570f6.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVJ5IJaNmHeaJWhsuFTjnGInNShLT0zvw',
    appId: '1:770345713614:ios:4861e192aa6c349bb8f59f',
    messagingSenderId: '770345713614',
    projectId: 'paeria-570f6',
    storageBucket: 'paeria-570f6.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuxL0j1qFW1jxnVpjex9rkaOkDEe6cm-U',
    appId: '1:770345713614:web:64b823b9896d1d23b8f59f',
    messagingSenderId: '770345713614',
    projectId: 'paeria-570f6',
    authDomain: 'paeria-570f6.firebaseapp.com',
    storageBucket: 'paeria-570f6.firebasestorage.app',
    measurementId: 'G-208L3S2WK6',
  );
}
